### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by svengcz** [vACDM/vacdm-plugin#12]
It is reported that the plugin freezes sometimes.
Currently is it not really reproducable or deducible where the error happens.

Ideas:
- The global lock is not fine granular enough and blocks the system if some network connections take longer
 - Check if the TLS-connection is kept alive (reestablishing TLS connection can take several seconds)
- The logging takes longer
 - @Phil061995 @Frenkii Are you using debug-logging or the default logging?
 - @Phil061995 @Frenkii Is the plugin running for a longer time and are the logfile big?

**Comment by Phil061995** [comment]
Maybe we should do a Delivery session on a friday evening at Frankfurt. There you could see the performance issues for sure and we have 3 hours with live traffic to test it.

I'm running the plugin in default mode. During events the plugin runs for around 3 hours.

**Comment by LeoKle** [comment]
@Phil061995 after #17 could we reinvestigate this issue?

**Comment by LeoKle** [comment]
No more reported performance issues.
Issue fixed.
