### ISSUE TITLE
[Improvement] Runway Configuration

### ISSUE THREAD

**Issue by LeoKle** [vACDM/vACDM-Plugin#22]
It might make more sense to take the runway configuration from the client of the tower controller.
As he will always have the correct one, while Delivery might select a different configuration causing a bottleneck.

**Comment by Frenkii** [comment]
The exact runway config should be irrelevant, because the backend assigns the pilots to the runways that are selected via the ES list. The backend doesent know the runway config at all.

**Comment by LeoKle** [comment]
Doesn't this mean that the rate of aircraft is reduced if the controller selected the wrong runway configuration?

**Comment by Frenkii** [comment]
No, every runway has its own capacity (except usage of alias) individually.
