### ISSUE TITLE
[Feature] ECFMP Flow Measures

### ISSUE THREAD

**Issue by LeoKle** [vACDM/vacdm-plugin#3]
Purpose: 
1. Display all flow measures pilot is subject to in TagItem
2. Display all flow measures applying to airport in a separate list

[Branch](https://github.com/vACDM/vACDM-Plugin/tree/feature/ecfmp-measures)

**Comment by LeoKle** [comment]
1. completed

**Comment by Phil061995** [comment]
Color Request for the displayed MDI.

TTOT between two outbounds with same DEST and FM, if differences between TTOTs for is > MDI green, if < MDI orange.

**Comment by Frenkii** [comment]
The backend already takes care of the MDI values and assigns TTOTs accordingly. It is therefore assured that the MDI value is valid between all flight with the same measures

**Comment by LeoKle** [comment]
closing this issue for now.

ECFMP TagItems are implemented. UI will be postponed to V2.
