### ISSUE TITLE
Correlation Mode Easy shouldn't be necessary

### ISSUE THREAD

**Issue by Frenkii** [vACDM/vacdm-plugin#33]
The Plugin needs Euroscopes Correlation Mode set to easy in order to work.
If we want to support as many vACCs as possible, we need to investigate if there is any chance to get rid of the correlated functions inside the plugin.

**Comment by LeoKle** [comment]
The problem is caused by using Euroscopes CRadarTarget however in C and S mode they can be invalid as it simulates an uncorrelated radar target.
This can be resolved using CFlightPlan instead.

Required fixes:
- [x] data sending
- [ ] display of received data
- [ ] Tag Item Functions

**Comment by LeoKle** [comment]
waiting for feedback from participating vACCs
