### ISSUE TITLE
Delete Times

### ISSUE THREAD

**Issue by Phil061995** [vACDM/vACDM-Plugin#4]
All **actual** times should be deletable if the controller clicked on the wrong item or a pilot need to cancel a request. 

TOBT and TSAT should be deleted if the controller enters a blank TOBT (no ready time => no TSAT). This option should also be used if the TOBT is unknown.

**Comment by svengcz** [comment]
In which cases is the TOBT unknown?

How can it be differentiated if the TOBT is deleted, but the TSAT should still remain valid?
See the other ticket about the TOBT-TSAT issue

**Comment by Phil061995** [comment]
Without TOBT there is no TSAT anymore. In this case the TSAT need to be deleted as well. The TOBT could be unknown, if the pilot does not know when he will be ready.

**Comment by LeoKle** [comment]
@Phil061995 see PR #31 
I added reset functions for all user actions.
Let me know if there are additional we could add.
