### ISSUE TITLE
times reset after loading data from the server

### ISSUE THREAD

**Issue by Phil061995** [vACDM/vacdm-plugin#41]
Sometimes when times (TOBT) are entered and the plugin is still doing/loading something in the background, the manually entered times (for different aircraft) are resetted to the ones before. Especially if there is a lot to do/enter, that is annoying to verify the time is not resetted.

**Comment by LeoKle** [comment]
Given the new processing of updates introduced with v1.3.0, I'll close this issue for now.
Feel free to reopen this issue if this issue appears again in v1.3.0 and later versions or if you have a log file.
