### ISSUE TITLE
Capacity Availability Document

### ISSUE THREAD

**Issue by maxlk96** [vACDM/vacdm-plugin#42]
Hey, as a representative for Sweden FIR in VATSIM Scandinavia I have a question about the plugin

In Sweden we presently use [Robert Puigs CDM Plugin](https://github.com/rpuig2001/CDM), which utilizes his CAD to restrict rates when multiple flights have the same departure and destination aerodrome.

https://github.com/rpuig2001/Capacity-Availability-Document-CDM/tree/main

Does this plugin also utilize that, if not, would it be possible to integrate?

Thanks for helping us flow control, keep up the great work!

**Comment by Phil061995** [comment]
Would you need a specific time between two TTOTs or is a maximum rate per 10 minutes per SID/DEST also an option?

To have a specific time between two TTOTs could be difficult as we are working with 10 minute blocks. And as the outbound is able to push TSAT +/- 5 minutes, a 2 or 3 minute spacing would not have any benefit if both will call at the same time within their TSAT window.

**Comment by maxlk96** [comment]
Maybe @rpuig2001 could answer what would be better.

How would the plugin handle rates below 10/h if working rate/10 min, does it work with decimal numbers or running 10 min time periods?

> Would you need a specific time between two TTOTs or is a maximum rate per 10 minutes per SID/DEST also an option?
> 
> To have a specific time between two TTOTs could be difficult as we are working with 10 minute blocks. And as the outbound is able to push TSAT +/- 5 minutes, a 2 or 3 minute spacing would not have any benefit if both will call at the same time within their TSAT window.

**Comment by rpuig2001** [comment]
Hi all,
The CAD was mainly created to separate traffics between departure to the same destination airport.

As an example:
If we have two traffics to the same destination (Destination is set in the CAD as 6 - Meaning planes to this destination minimum time between TTOTs 10min). If both planes request start-up at the same time, the TTOTs will be separated by 10min.

**Comment by LeoKle** [comment]
Hi,

the plugin or the backend to be precise, which handles the CDM process, do not currently have the CAD functionality.
However it has already been requested as a feature. I have added in the [#feature-requests channel](https://discord.com/channels/802213274443579462/1226945524444168256) in the Discord, so we have a place to discuss it.

It will likely be added with version 2.
